### ISSUE TITLE
可以问下forbidden_roles的意义是什么吗？

### ISSUE THREAD

**Issue by hackerfj** [storyicon/grbac#2]
我因为看到里面有authorized_roles这个字段不是可以直接判断出是否可以访问此URL了吗，想问下加一个forbidden_roles的意义是什么？

**Comment by storyicon** [comment]
I'm sorry I'm late, it just provides `a mechanism of anti selection`. 
For example, for some interfaces, you have 99 roles belonging to `authorized_roles`  and 1 role belonging to `forbidden_roles` (such as employees who have left), you do not have to write a large number of authorized_roles

**Comment by hackerfj** [comment]
thank you！
